package com.inlandnwsurf.rest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "states")
public class State {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	private String id;
    
    @DynamoDBAttribute
	private String name;
    
    @DynamoDBAttribute
	private String abbv;
    
    @DynamoDBAttribute
	private String country;

}
