spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri:
database:
  dynamodb:
    local: false
    table: ${TABLE_NAME:surf-spots-dev}