
spring:
  profiles:
    active: local
server:
  port: 8080

---

spring:
  profiles: local
  amazon:
    dynamodb:
      endpoint: http://localhost:8000/
    aws:
      accesskey: none
      secretkey: none
      region: us-west-2
      
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true
      
---

spring:
  profiles: dev
  amazon:
    dynamodb:
      endpoint: http://localhost:8000/
    aws:
      accesskey: none
      secretkey: none
      region: us-west-2
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true
---

spring:
  profiles: prod
  amazon:
    dynamodb:
      endpoint: http://localhost:8000/
    aws:
      accesskey: none
      secretkey: none
      region: us-west-2
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
      