spring:
  application:
    name: ${APP_NAME:InlandNW-Surf-Service}
    debug : true
  profiles:
    active: local
logging:
  level:
    root: ${LOG_LEVEL:INFO}
server:
  port: 8080
management:
  server:
    port: 8081
springdoc:
  swagger-ui:
    path: /swagger
