spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri:
database:
  dynamodb:
    local: true
    table: ${TABLE_NAME:surf-spots-local}
    endpoint: http://localhost:8000/
    accesskey: dummy
    secretkey: dummy
